language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: iY1jlISfnqge1n/NSzoIRgcvzfnur2EDsALmhmebBg1A0HTAAahxBXfGbAt0hddD6gTD2xVUmN2uoE1qTF2xmBSKBPsXH6f5dzLXDIUvazbsoiJaV7IAdQn5KZwShql0Swd3SVwgeBT2T4eF8TkPwXTahzoC8Pa4kMaG2zSJVO8HXM6pgITkLP+c335Lf0g+WamD2eVHtZRAat9qNPzBp6Yb9cVOkwCPbgKffW7a+vvremy1Lh5+JUR38+PIa73/osbgYY7T8M2lAY/HHVZhWxrdRuq0hSSTMjVsPH/ejl/sW7aPOXl6zG9tJl+yRAflDZ3BpKBDBzhsrDctNyFpB+aRl6n/J3dqycuviUYISlzgOJCGZV0Ang98kEbblE6LEDpNZDyIRZatYdcVN4fcIqtivCafxlfn6B/lIY2DpTFZ3gTmQABtA6w64WqfpiwUteQsq+mwgqr8Xyoh6Qxm1nVBHWHqD9CQp7aexRKylUa6I7SwghoEJFOQ3R9ofuHJbxzdHpR7Dg6dyNc5hKK4e94sHm3Gm7pruxhAgxJWZB3YgJKcguW1n573FGD/utGpVdWGJ1NCFOShIzWSXmOYeNi4DFwtcQnNJFXrmjhzFkO9bIhpsTcowLxST+6/eqNVBvCe49jwtaJwgDIukcyl1YVh1zmKACrHS09Thi8o9sc=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
